version: "3.9"
services:
  nginx54:
    image: nginx:alpine
    container_name: mapos-54-nginx
    hostname: nginx
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "../:/var/www/html"
      - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    networks:
      nginx_network:
        ipv4_address: 10.0.2.54
      network54:
        ipv4_address: 10.0.54.2
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    env_file:
      - ".env"
    command: /bin/sh -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php-fpm54
      - mysql54

  php-fpm54:
    container_name: mapos-54-php-fpm
    hostname: php-fpm
    build:
      context: ./etc/php
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./etc/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
      - "../:/var/www/html"
    networks:
      network54:
        ipv4_address: 10.0.54.4

  composer54:
    container_name: mapos-54-composer
    hostname: composer
    build:
      context: ./etc/composer
      dockerfile: Dockerfile
    volumes:
      - "../:/app"
    networks:
      network54:
        ipv4_address: 10.0.54.5
    command: install --ignore-platform-reqs --no-scripts



  mysql54:
    image: mysql:${MYSQL_MAPOS_VERSION}
    container_name: mapos-54-mysql
    hostname: mysql54
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_MAPOS_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_MAPOS_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_MAPOS_USER}
      - MYSQL_PASSWORD=${MYSQL_MAPOS_PASSWORD}
    networks:
      network54:
       ipv4_address: 10.0.54.3
    ports:
      - "${MYSQL_MAPOS_PORT}:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"



networks:
  network54:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.54.0/24
          gateway: 10.0.54.1
  nginx_network:
    external: true